import type { Metadata } from "next"
import { Albert_Sans } from "next/font/google"
import "./globals.css"
import { Navbar } from "@/components/navigation/Navbar"

const albertSans = Albert_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Générations Connectées",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="fr">
			<body className={`${albertSans.className} h-full w-full`}>
				<Navbar />

				<main className="py-28 px-5 md:px-44">{children}</main>
			</body>
		</html>
	)
}
